runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://heroku_2znvp2lz:3md5q102cieg16bpjvip840qim@ds127730.mlab.com:27730/heroku_2znvp2lz
  APP_ID: YCT001
  MASTER_KEY: YCT001_MASTERKEY
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  